name: Deploy for QA

on: 
  #run when pull request
  pull_request:
    branches: [ main ]
  
  # manual button 
  workflow_dispatch:

jobs: 
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install
      

      - name: Run Linting
        run: npm run lint
      

      - name: Run Unit Tests
        run: |
          npm run test-react || echo "test-react failed"
          npm run test-API || echo "test-API failed"
          npm run test || echo "test failed"


  deploy-to-qa:
    needs: build-and-test
    runs-on: ubuntu-latest
    #deploy if build and test succeeded
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'

    steps:
      - name: SSH to AWS QA Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TESTING_INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /home/ubuntu/Devops_assignment-3
            git fetch origin
            # this will try to pull changes from the branch that made the pull request
            git checkout ${{ github.head_ref || 'main' }}
            git pull origin ${{ github.head_ref || 'main'}} 
            npm install
            npm run build
            pm2 restart all 
     

      # may need more work 
      - name: Send Email to QA 
        if: success()
        uses: dawid66/action-send-mail@v3
        with: 
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME}}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Deployment Succesful - Ready for QA testing 
          to: sajid.ali@giki.edu.pk
          from: Github Actions
          body: |
            Hello QA, 
          
            The app is deployed succesfully. Changes are available for evaluation
            Branch: ${{ github.head_ref || 'main' }}
            Access the app here: http://${{ secrets.TESTING_INSTANCE_IP }}
         
    



