name: Deploy for QA

on: 
  #run when pull request
  pull_request:
    branches: [ main ]
  
  # manual button 
  workflow_dispatch:

jobs: 
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Run Linting
        run: | 
          npm run lint
          npm run lint:fix
        continue-on-error: true # prevent linting errors from crashing the whole workflow

      - name: Run Unit Tests
        run: |
          npm run test-react || echo "test-react failed"
          npm run test-API || echo "test-API failed"
          npm run test || echo "test failed"


  deploy-to-qa:
    needs: build-and-test
    runs-on: ubuntu-latest
    #deploy if build and test succeeded
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'

    steps:
      - name: SSH to AWS QA Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TESTING_INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /home/ubuntu/Devops_assignment-3
            git fetch origin
            # this will try to pull changes from the branch that made the pull request
            git checkout ${{ github.head_ref || 'main' }}
            git pull origin ${{ github.head_ref || 'main'}} 
            npm install
            npm run build
            pm2 restart all 
     

      
      - name: Send Email to QA on success 
        if: success()
        uses: dawidd66/action-send-mail@v3
        with: 
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME}}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Deployment Succesful: Branch ${{ github.head_ref }}"  
          to: msajidaligiki@gmail.com
          from: Github Actions 2022477+2022623
          body: |
            Hello QA, 
          
            The app is deployed succesfully with changes from branch [${{ github.head_ref }}]. Changes are available for evaluation
            Branch: ${{ github.head_ref || 'main' }}
            Access the app here: http://${{ secrets.TESTING_INSTANCE_IP }}
         
      - name: Send Email to Relevant on Failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with: 
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME}}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "QA Deployment FAILED: Branch ${{ github.head_ref }}"
          to: msajidaligiki@gmail.com, ${{ github.actor }}@users.noreply.github.com
          from: Github Actions 2022477+2022623
          body: | 
            Hello, 

            The QA deployment for branch [${{ github.head_ref }}] has FAILED. 
            Details:
            - Initiated by $${{ github.actor }}
            - View Error Logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} # resolve to link for actions run
